### ISSUE TITLE
Cholmod error "problem too large" at file 

### ISSUE THREAD

**Issue by jaempawi** [campbio/Manuscripts#17]
Hello, I am running a few samples through Seurat curated workflow. Everything is fine until finding HVG step where it shows this error: `Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102`. My scaled data is a  [17284x151789] matrix. Let me know if you need more information. Thank you in advance!

**Comment by joshua-d-campbell** [comment]
Hi @jaempawi, thanks for using our tools. I'm guessing you are trying to singleCellTK? Just FYI, there is a separate issues page for that repo [here](https://github.com/compbiomed/singleCellTK/issues). Could you let me know what version of the software you are using? We have made several updates to make the Seurat workflow more efficient in the latest version on Github (v2.7.1). That may help. How are you importing the matrix? I also just want to make sure it is being stored in sparse format. Finally, how much memory do you have available?

**Comment by jaempawi** [comment]
Hello Joshua,

I am sorry for late response as I have figured out how to overcome that error. However, my team and I are optimizing our pipeline for QC and wondering if we could adjust the argument for scdblFinder. We lose a lot of cells after filtering the “doublet” cells out.

Looking forward to hearing from you.

Best,
Jenny Empawi

From: Joshua D. Campbell ***@***.***>
Date: Thursday, September 29, 2022 at 12:37 PM
To: campbio/Manuscripts ***@***.***>
Cc: jaempawi ***@***.***>, Mention ***@***.***>
Subject: Re: [campbio/Manuscripts] Cholmod error "problem too large" at file (Issue #17)

Hi @jaempawi<https://github.com/jaempawi>, thanks for using our tools. I'm guessing you are trying to singleCellTK? Just FYI, there is a separate issues page for that repo here<https://github.com/compbiomed/singleCellTK/issues>. Could you let me know what version of the software you are using? We have made several updates to make the Seurat workflow more efficient in the latest version on Github (v2.7.1). That may help. How are you importing the matrix? I also just want to make sure it is being stored in sparse format. Finally, how much memory do you have available?

**Comment by joshua-d-campbell** [comment]
Hi @jaempawi, you can specify parameters of individual algorithms using the YAML file. See [here](https://camplab.net/sctk/v2.7.1/articles/cmd_qc.html#specify-parameters-using-yaml-file) for instructions for v2.7.1. Just let us know if you have other questions or problems. 

As a side note, we often don't directly filter on doublet calls but rather use that metric as a way to assess clusters in the downstream analysis. We generally perform filtering on "total" or "detected" counts. Sometime we also filter on decontX contamination if the ambient RNA levels are high for a particular dataset. But it is a good idea to check that your cell clusters are enriched for doublet scores, high contamination levels, etc in the downstream analysis. 

I'm going to close this particular issue since it is on our "Manuscript" repo. If yo have other questions/issues, feel free to reach out on the singleCellTK [GitHub page](https://github.com/compbiomed/singleCellTK/issues).
